openapi: 3.0.0
info:
  title: Person API
  version: 1.0.0
paths:
  /api/v1/persons/create:
    post:
      summary: Create a person
      operationId: createPerson
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
  /api/v1/persons/updateLocation:
    put:
      summary: Update or create someone's location
      operationId: updateLocation
      parameters:
        - name: id
          in: query
          required: true
          description: ID of the person
          schema:
            type: integer
        - name: latitude
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: longitude
          in: query
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
  /api/v1/persons/getByLocation:
    get:
      summary: Retrieve people around query location
      operationId: getPeopleAroundLocation
      parameters:
        - name: latitude
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: longitude
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: radius
          in: query
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
  /api/v1/persons/getPersons:
    get:
      summary: Retrieve a person by ID
      operationId: getPersonById
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: array
            items:
              type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: number
          format: long
        name:
          type: string
    Location:
      type: object
      properties:
        referenceId:
          type: number
          format: long
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double